# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/6Pwc8w6J1M/australasia.  Olson data version 2013d
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Pacific::Palau;
{
  $DateTime::TimeZone::Pacific::Palau::VERSION = '1.60';
}
BEGIN {
  $DateTime::TimeZone::Pacific::Palau::AUTHORITY = 'cpan:DROLSKY';
}

use strict;

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Pacific::Palau::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY, #    utc_start
59958198124, #      utc_end 1900-12-31 15:02:04 (Mon)
DateTime::TimeZone::NEG_INFINITY, #  local_start
59958230400, #    local_end 1901-01-01 00:00:00 (Tue)
32276,
0,
'LMT',
    ],
    [
59958198124, #    utc_start 1900-12-31 15:02:04 (Mon)
DateTime::TimeZone::INFINITY, #      utc_end
59958230524, #  local_start 1901-01-01 00:02:04 (Tue)
DateTime::TimeZone::INFINITY, #    local_end
32400,
0,
'PWT',
    ],
];

sub olson_version { '2013d' }

sub has_dst_changes { 0 }

sub _max_year { 2023 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

