# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/6Pwc8w6J1M/northamerica.  Olson data version 2013d
#
# Do not edit this file directly.
#
package DateTime::TimeZone::America::Dominica;
{
  $DateTime::TimeZone::America::Dominica::VERSION = '1.60';
}
BEGIN {
  $DateTime::TimeZone::America::Dominica::AUTHORITY = 'cpan:DROLSKY';
}

use strict;

use Class::Singleton 1.03;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::America::Dominica::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY, #    utc_start
60289416396, #      utc_end 1911-07-01 04:06:36 (Sat)
DateTime::TimeZone::NEG_INFINITY, #  local_start
60289401660, #    local_end 1911-07-01 00:01:00 (Sat)
-14736,
0,
'LMT',
    ],
    [
60289416396, #    utc_start 1911-07-01 04:06:36 (Sat)
DateTime::TimeZone::INFINITY, #      utc_end
60289401996, #  local_start 1911-07-01 00:06:36 (Sat)
DateTime::TimeZone::INFINITY, #    local_end
-14400,
0,
'AST',
    ],
];

sub olson_version { '2013d' }

sub has_dst_changes { 0 }

sub _max_year { 2023 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}



1;

